# Info
title: "Alexander Mezhov"
author: "Alexander Mezhov"
email: "as.mezhov@gmail.com"
repository: "AlexMAS/AlexMAS.github.io"

# Profiles
github_username: "AlexMAS"
twitter_username: "amezhov"
facebook_username: "a.mezhov"
linkedin_username: "mezhov"

# Services
disqus: "alexander-mezhov"
yandexMetrika: "46776420"
googleAnalytics: "UA-110188612-1"

# Handling
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
exclude: [ ".git", ".vscode" ]
keep_files: [ ".git" ]
encoding: "utf-8"
safe: false

# Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Posts
excerpt_separator: "<!--more-->"
permalink: pretty

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"
permalink: "/:categories/:year/:month/:title/"

# Serving
baseUrl: ""
url: "http://localhost:4000"
host: 127.0.0.1
port: 4000
detach: false

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jemoji
